name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  env:
    name: Test env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Conda env
        uses: mamba-org/setup-micromamba@63849fa5f38bd7edfb2c4b518206ea9eee3502d1
        with:
          environment-file: environment.yml
          environment-name: test-env
