name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  env:
    name: Test env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Conda env
        uses: mamba-org/setup-micromamba@2b72821d5ad7f6da3c003a3684ce341bf187b46f
        with:
          environment-file: environment.yml
          environment-name: test-env
