name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  env:
    name: Test env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Conda env
        uses: mamba-org/setup-micromamba@54d4d5980e1a4aa7cdc8b050cf2d19b7e262ce18
        with:
          environment-file: environment.yml
          environment-name: test-env
